[[pages]]
path = "pages/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/ml_inference.py"
name = "Model Inference"
icon = "ğŸ§ "

[[pages]]
path = "pages/visualize.py"
name = "Iris Visualization"
icon = "ğŸ“ˆ"
